"""
HealthDesk — User Model (MongoDB Document Schema)
====================================================
Since we use pymongo directly, this file defines:
1. The USER SCHEMA as a Python dataclass/dict spec (documentation + validation)
2. A UserDocument class with CRUD helpers
3. Password hashing utilities

WHY not Django ORM here?
We use pymongo for app data because:
- MongoDB document model fits healthcare data perfectly (flexible schema)
- No ORM translation overhead for complex nested documents (e.g., medical history)
- Full access to MongoDB aggregation pipelines, geospatial queries

Django ORM (SQLite) is used ONLY for:
- JWT token blacklisting (simplejwt.token_blacklist)
- Django admin session management

ROLES:
  PATIENT → Books appointments, manages own records
  DOCTOR  → Manages appointments, views patient records (Phase 2)
  ADMIN   → Platform administration
  DONOR   → Blood donor pool (Phase 4)
"""

from datetime import datetime, timezone
from typing import Optional, Dict, Any

import bcrypt
from pymongo import IndexModel, ASCENDING
from bson import ObjectId

from core.db import get_db, Collections


# ─── Role & Blood Group Constants ─────────────────────────────────────────────
class Role:
    PATIENT = 'PATIENT'
    DOCTOR = 'DOCTOR'
    ADMIN = 'ADMIN'
    DONOR = 'DONOR'
    ALL = [PATIENT, DOCTOR, ADMIN, DONOR]


class BloodGroup:
    A_POS = 'A+'
    A_NEG = 'A-'
    B_POS = 'B+'
    B_NEG = 'B-'
    AB_POS = 'AB+'
    AB_NEG = 'AB-'
    O_POS = 'O+'
    O_NEG = 'O-'
    UNKNOWN = 'UNKNOWN'
    ALL = [A_POS, A_NEG, B_POS, B_NEG, AB_POS, AB_NEG, O_POS, O_NEG, UNKNOWN]


# ─── MongoDB Document Schema (for documentation + validation reference) ────────
USER_SCHEMA = {
    # Identity
    '_id': 'ObjectId — auto-generated by MongoDB',
    'email': 'str — unique, indexed, primary login identifier',
    'first_name': 'str',
    'last_name': 'str',
    'phone': 'str | None',
    'date_of_birth': 'datetime | None',
    'gender': 'str | None',
    'profile_photo_url': 'str | None',

    # Auth
    'password_hash': 'str — bcrypt hashed, never plaintext',
    'is_active': 'bool — default True',
    'is_verified': 'bool — email verified flag',

    # Role
    'role': 'str — one of Role.ALL',

    # Healthcare-specific
    'blood_group': 'str — one of BloodGroup.ALL',
    'emergency_contact': {
        'name': 'str | None',
        'phone': 'str | None',
    },
    'address': {
        'street': 'str | None',
        'city': 'str | None',
        'state': 'str | None',
        'zip': 'str | None',
    },
    'blood_donor_available': 'bool — default False',

    # Timestamps
    'created_at': 'datetime (UTC)',
    'updated_at': 'datetime (UTC)',
    'last_login': 'datetime | None',
}


class UserDocument:
    """
    MongoDB CRUD operations for the users collection.
    All methods return plain Python dicts (the raw MongoDB documents).

    WHY a class with static methods?
    - Keeps all user-related DB logic in one place
    - Easy to mock in tests
    - No ORM magic — explicit and easy to debug
    """

    @staticmethod
    def collection():
        """Returns the users MongoDB collection."""
        return get_db()[Collections.USERS]

    @staticmethod
    def ensure_indexes():
        """
        Create MongoDB indexes.
        Call this once at startup (or via management command).
        WHY indexes? Without them, find_one({'email': ...}) does a full collection scan.
        With an index on email, it's O(log n) — instant even with millions of users.
        """
        collection = UserDocument.collection()
        collection.create_indexes([
            IndexModel([('email', ASCENDING)], unique=True, name='email_unique'),
            IndexModel([('role', ASCENDING)], name='role_index'),
            IndexModel([('blood_group', ASCENDING)], name='blood_group_index'),
        ])

    @staticmethod
    def hash_password(plain_password: str) -> str:
        """Hash a password using bcrypt. Never store plaintext passwords."""
        salt = bcrypt.gensalt()
        hashed = bcrypt.hashpw(plain_password.encode('utf-8'), salt)
        return hashed.decode('utf-8')

    @staticmethod
    def check_password(plain_password: str, password_hash: str) -> bool:
        """Verify a password against its bcrypt hash."""
        return bcrypt.checkpw(
            plain_password.encode('utf-8'),
            password_hash.encode('utf-8')
        )

    @staticmethod
    def create(data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Insert a new user document.
        Returns the created document with _id as string.
        """
        now = datetime.now(timezone.utc)
        document = {
            'email': data['email'].lower().strip(),
            'first_name': data['first_name'].strip(),
            'last_name': data['last_name'].strip(),
            'phone': data.get('phone'),
            'date_of_birth': data.get('date_of_birth'),
            'gender': data.get('gender'),
            'profile_photo_url': None,
            'password_hash': UserDocument.hash_password(data['password']),
            'is_active': True,
            'is_verified': False,
            'role': data.get('role', Role.PATIENT),
            'blood_group': data.get('blood_group', BloodGroup.UNKNOWN),
            'blood_donor_available': data.get('blood_donor_available', False),
            'emergency_contact': {
                'name': data.get('emergency_contact_name'),
                'phone': data.get('emergency_contact_phone'),
            },
            'address': {
                'street': data.get('address_street'),
                'city': data.get('address_city'),
                'state': data.get('address_state'),
                'zip': data.get('address_zip'),
            },
            'created_at': now,
            'updated_at': now,
            'last_login': None,
        }

        result = UserDocument.collection().insert_one(document)
        document['_id'] = str(result.inserted_id)
        document.pop('password_hash')  # Never return password hash
        return document

    @staticmethod
    def find_by_email(email: str) -> Optional[Dict[str, Any]]:
        """Find a user by email address (case-insensitive)."""
        return UserDocument.collection().find_one(
            {'email': email.lower().strip()}
        )

    @staticmethod
    def find_by_id(user_id: str) -> Optional[Dict[str, Any]]:
        """Find a user by MongoDB ObjectId string."""
        try:
            doc = UserDocument.collection().find_one({'_id': ObjectId(user_id)})
            if doc:
                doc['_id'] = str(doc['_id'])
            return doc
        except Exception:
            return None

    @staticmethod
    def update(user_id: str, data: Dict[str, Any]) -> bool:
        """Update user fields. Returns True if document was modified."""
        data['updated_at'] = datetime.now(timezone.utc)
        data.pop('password_hash', None)  # Safety: never update password via this method
        data.pop('email', None)          # Email changes need special verification flow

        result = UserDocument.collection().update_one(
            {'_id': ObjectId(user_id)},
            {'$set': data}
        )
        return result.modified_count > 0

    @staticmethod
    def serialize(doc: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert a MongoDB document to a safe JSON-serializable dict.
        Removes sensitive fields and converts ObjectId/datetime to strings.
        """
        if not doc:
            return {}
        return {
            'id': str(doc.get('_id', '')),
            'email': doc.get('email', ''),
            'first_name': doc.get('first_name', ''),
            'last_name': doc.get('last_name', ''),
            'full_name': f"{doc.get('first_name', '')} {doc.get('last_name', '')}".strip(),
            'phone': doc.get('phone'),
            'date_of_birth': str(doc['date_of_birth']) if doc.get('date_of_birth') else None,
            'gender': doc.get('gender'),
            'profile_photo_url': doc.get('profile_photo_url'),
            'role': doc.get('role', Role.PATIENT),
            'blood_group': doc.get('blood_group', BloodGroup.UNKNOWN),
            'blood_donor_available': doc.get('blood_donor_available', False),
            'is_active': doc.get('is_active', True),
            'is_verified': doc.get('is_verified', False),
            'emergency_contact': doc.get('emergency_contact', {}),
            'address': doc.get('address', {}),
            'created_at': doc['created_at'].isoformat() if doc.get('created_at') else None,
            'last_login': doc['last_login'].isoformat() if doc.get('last_login') else None,
        }
